
name: test building docker and singularity and pushing to ghcr

on:
  push:
    branches:
      - main

#  release: 
#    types: [published]
#    branches: # Edit the branches here if you want to change deploy behavior
#      - ghci #main

jobs:
  test: 
    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: truth
        run: /bin/true
